name: $(BuildDefinitionName)_$(SourceBranchName)_$(BuildID)

variables:
  - name: DOCKER_BUILDKIT
    value: 1
    
trigger:
  branches:
    include:
      - master
      - refs/tags/*
  paths:
    exclude:
      - '**/*.md'
      - .vscode/*
      - .git*
      - .editorconfig

pr:
  - master
  - release/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
