name: $(BuildDefinitionName)_$(SourceBranchName)_$(BuildID)

variables:
  - name: DOCKER_BUILDKIT
    value: 1
  - group: AWS
  - name: ENABLE_DOCKER_PUBLISH
    value: ${{ or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/tags')) }}
  - name: ENABLE_GLOBAL_RELEASE
    value: ${{ or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/tags')) }}

trigger:
  branches:
    include:
      - master
      - refs/tags/*
  paths:
    exclude:
      - '**/*.md'
      - .vscode/*
      - .git*
      - .editorconfig

pr:
  - master
  - release/*

jobs:
- job: Job1
  displayName: My First Job
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

- job: Job2
  displayName: My Second Job
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
